# Generated by Django 5.1.2 on 2024-12-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=10)),
                ('Pin', models.CharField(max_length=4)),
                ('Mobile_Number', models.CharField(max_length=12)),
                ('Acc_No', models.CharField(max_length=11, unique=True)),
                ('Balance', models.IntegerField()),
            ],
        ),
    ]
